name: baiduad
description: 百度广告flutter版本
version: 0.0.1
homepage: https://github.com/gstory0404/baiduad

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  plugin:
    platforms:
      android:
        package: com.gstory.baiduad
        pluginClass: BaiduadPlugin
      ios:
        pluginClass: BaiduadPlugin